### ISSUE TITLE
seems pointless

### ISSUE THREAD

**Issue by yairEO** [radkodinev/jquery-classes#1]
you can do all that already using jquery's `toggleClass`.. can't believe you actually spent time making this

**Comment by radkodinev** [comment]
@yairEO I can't believe you actually spent time opening this issue. This seems much more pointless to me. Do you open similar issues in each Github repo you don't use or find useless? Honestly, I'm greatly amazed. Nobody is forcing you to use anything - you have the complete freedom to not use this jQuery plugin if you find it useless. Why I made this project and published it is totally my concern and it shouldn't bother you at all.

**Comment by yairEO** [comment]
ok bro relax no need to get super mad, it just seems weird, is all.

**Comment by radkodinev** [comment]
@yairEO I'm not mad, I'm just amazed :)
